pull_request_rules:
  - name: automatic merge on depenabot pull requests
    conditions:
      - author=dependabot[bot]
      - status-success=continuous-integration/travis-ci/pr
    actions:
      merge:
        method: merge
